import type { Metadata } from 'next';
import { Be_Vietnam_Pro, Rubik, Ubuntu } from 'next/font/google';

import StyledComponentsRegistry from '@/infra/libs/styling/styled-components/registry';

import { Providers } from './providers';

const rubik = Rubik({
	subsets: ['latin'],
	weight: ['700'],
	display: 'swap',
	variable: '--font-highlight',
});

const ubuntu = Ubuntu({
	subsets: ['latin'],
	weight: ['500', '700'],
	display: 'swap',
	variable: '--font-heading',
});

const beVietnamPro = Be_Vietnam_Pro({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	display: 'swap',
	variable: '--font-body',
});

export const metadata: Metadata = {
	title: 'Code Challenges',
	description: 'Generated by create next app',
};

const fonts = `${rubik.variable} ${ubuntu.variable} ${beVietnamPro.variable}`;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body className={fonts}>
				<StyledComponentsRegistry>
					<Providers>{children}</Providers>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
